---
title: Readings
link-bibliography: true
suppress-bibliography: true
link-citations: false
citations-hover: false
csl: apa-cv.csl
---

Here are the readings for each week. Please have the readings done _before_ the corresponding class. I'll try not to assign too much reading, so please come ready to discuss! 

(Please also don't make me regret saying this but in case you absolutely can't get all the reading done, they're in order of importance so start at the top each week.)


## Week 2, Feb 7: encoding data to visuals; making meaning of data

* @Wilke2019 chapters 2 & 3
* @Cairo2019 intro (on Blackboard)
* Pick one (or both. They're both great, but if you only choose one I'd go with the podcast.):
  * Read @DIgnazio2015
  * Listen to PolicyViz, @Schwabish2018
* Watch @Kosara2019 (5 min video)

## Week 3, Feb 14: writing good code; color

* @Wilke2019 chapters 4, 6, 17 (color, amounts, proportional ink)
* @W.C.G2023 chapters 1 & 9 (okay to skim as a code reference) (data visualization, layers)

## Week 4, Feb 21: text & annotation

* Pick one (or both) of these styleguides to browse through. Take note of how they use color, text, annotations, and iconography, and what suggestions they have on other elements (labeling axes, direct labeling of points, style of titles, placement and rotation of labels, etc). How do these rules carry over between chart types or for different audiences? How strongly do they create a recognizable visual style or brand?
  * @Urban2023
  * @WHO2023 (it's not super clear but you have to click through to each section)

## Week 5, Feb 28: uncertainty, distributions, making good decisions

* Listen to Data Stories, @B.S2019
* @Wilke2019 chapters 7, 9, 10, 13, 14, 20 (okay to skim)
* Pick one. If you post on Discord or tell us in class what you learned, you'll get 1 participation point:
  * @Cairo2019 chapter 1 (on Blackboard)
  * @Smith2023
  * Listen to @B.S2018a

## Week 6, March 6: responsibility

Focus on finishing the case studies---only one reading and it's a podcast

* Listen to @Schwabish2021c and browse through the accessibility tool they discuss: @Elavsky2022

## Week 7, March 13: accessibility and empathy

* I forgot to put last week's podcast on Blackboard, so if you missed it please listen to it for this week
* @Makulec2020
* @BocoupLLC2017
* @Elghany2023

## Week 8, March 27: midterm projects

* @Yau2017

## Week 9, April 3: intro to spatial data viz

* @Wilke2019 chapter 15
* Listen to @swd2021

## Week 10, April 10: color, text, annotations part 2

* @Muth2024b
* @Muth2024a
* Listen or read (or both): @ODonohue2020
* @L.N.M2019---skim / use just as a reference

## Week 11, April 17: responsibility and context

* @Sadler2016
* @Simmon2024a
* @Wiseman2015

## Week 12, April 24: storytelling with maps

* @Seaberry2018a (sorry for assigning my own project, just skim it)
* @Cheysson
* @Abbasi2022
